volumes:
  mongodb_volume:

services:
  frontend:
    build: frontend/
    restart: always
    ports:
      - 8080:8080

  backend:
    build: backend/
    restart: always
    ports:
    - 5000:5000
    environment:
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
    - mongodb_volume:/data/db
